apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  workspaces:
    - name: cdcon-workspace
  params:
    - name: APP_PATH
      description: "Path to the dockerfile within the repo"
  resources:
    outputs:
      - name: app-image
        type: image
  steps:
    - name: build-app-image-with-kaniko
      image: "gcr.io/kaniko-project/executor:latest"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.cdcon-workspace.path)/$(params.APP_PATH)/Dockerfile
        - --destination=$(resources.outputs.app-image.url)
#        - --context=dir://$(workspaces.cdcon-workspace.path)/$(params.APP_PATH)
