apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: serviceFile
      description: "path to the service YAML file"
      type: string
      default: "services/deploy.yaml"
    - name: appName
      description: "deployment label"
      type: string
    - name: nodePort
      description: "exposing container port"
      type: string
  workspaces:
    - name: cdcon-workspace
  resources:
    inputs:
      - name: app-image
        type: image
  steps:
    - name: update-service-yaml
      image: alpine
      script: |
        sed -i -e "s;__IMAGE__;$(resources.inputs.app-image.url);g" -e "s;__APP__;$(params.appName);g" -e "s;__NODEPORT__;$(params.nodePort);g" $(workspaces.cdcon-workspace.path)/$(params.serviceFile)
    - name: print-service-yaml
      image: alpine
      script: |
        cat $(workspaces.cdcon-workspace.path)/$(params.serviceFile)
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.cdcon-workspace.path)/$(params.serviceFile)"
