#apiVersion: serving.knative.dev/v1alpha1
#kind: Service
#metadata:
#  name: cdcon-app
#  namespace: default
#spec:
#  runLatest:
#    configuration:
#      revisionTemplate:
#        spec:
#          container:
#            image: __IMAGE__


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP__
  labels:
    app: __APP__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __APP__
  template:
    metadata:
      labels:
        app: __APP__
    spec:
      containers:
        - name: cdcon-hello-app
          image: __IMAGE__
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: __APP__
  labels:
    app: __APP__
spec:
  type: NodePort
  ports:
    - port: 8080
      name: __APP__
      nodePort: __NODEPORT__
  selector:
    app: __APP__
