apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-to-build-app-image
spec:
  workspaces:
    - name: cdcon-workspace
  params:
    - name: DOCKERFILE
      description: "Path to the dockerfile"
      type: string
      default: "Dockerfile"
  resources:
    - name: app-image
      type: image
  tasks:
    - name: clone-app-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/pritidesai/cdcon2020.git
        - name: subdirectory
          value: app
      workspaces:
        - name: output
          workspace: cdcon-workspace
    - name: build-app-image
      taskRef:
        name: build-app-image
      runAfter: [ clone-app-source ]
      workspaces:
        - name: cdcon-workspace
          workspace: cdcon-workspace
      resources:
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)

