apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-to-build-image-notify-cleanup

spec:

  params:
    - name: appRepo
      description: "Application repo location"
      type: string
      default: "https://github.com/pritidesai/cdcon2020.git"
    - name: appPath
      description: "use case location"
      type: string

  workspaces:
    - name: cdcon-workspace

  resources:
    - name: app-image
      type: image

# Tasks
  tasks:

    # Git Clone App Repo
    - name: clone-app-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.appRepo)
      workspaces:
        - name: output
          workspace: cdcon-workspace

    # Build an application, run after git clone is successful
    - name: build-app-image
      taskRef:
        name: build-image
      runAfter: [ clone-app-source ]
      params:
        - name: appPath
          value: $(params.appPath)
      resources:
        outputs:
          - name: app-image
            resource: app-image
      workspaces:
        - name: cdcon-workspace
          workspace: cdcon-workspace

    # Run e2e Tests
    - name: run-e2e-tests
      taskSpec:
        steps:
          - name: e2e-tests
            image: "ubuntu"
            script: |
              exit 1
      runAfter: [ build-app-image ]

    # Deploy App Image
    - name: deploy-app-image
      taskRef:
        name: deploy-using-kubectl
      runAfter: [ run-e2e-tests ]
      resources:
        inputs:
          - name: app-image
            resource: app-image
      workspaces:
        - name: cdcon-workspace
          workspace: cdcon-workspace

  finally:

    - name: cleanup
      taskSpec:
        steps:
          - name: finish-cleanup
            image: "ubuntu"
            script: |
              echo Finished cleaning up the cluster after running e2e tests.

    - name: notify-test-results
      taskSpec:
        steps:
          - name: notification
            image: "ubuntu"
            script: |
              echo Sent Slack message with the test results.
